name: Dockerfile

on:
  push:
    branches: main
    paths:
      - Dockerfile
  pull_request:
    paths:
      - Dockerfile
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [
          "web",
          "api"
        ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        id: build
        with:
          file: './Dockerfile.${{ matrix.image }}'
          secrets: github_token=${{ secrets.GITHUB_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha
          push: false
